name: Redeemer
main: fr.syfizz.minecraft.redeemer.Redeemer
version: 1.0.3
author: SyFizz_
commands:
  redeem:
    description: "Redeem an code!"
    usage: /redeem [code/reload]
    aliases: ["code", "redeemer"]